### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by mhaagens** [lukeed/templite#2]
Do you have any performance benchmarks against popular templating libraries?
Curious to see how it stacks up against EJS/HAML etc.

**Comment by lukeed** [comment]
Hey,

Not sure that this would make sense or be a fair comparison. They both (and most do) evaluate _beforehand_ in order to execute their helpers. 

Templite is basically just a `RegExp` with named patterns -- not nearly as powerful or even in ballpark.

I can benchmark against similar, simple libs... but I don't know of any off-hand, which is why this is a thing 😄
